# Generated by Django 4.0.6 on 2022-08-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_band_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('Not Contacted', 'Not Contacted'), ('Contacted', 'Contacted'), ('Followed Up With', 'Followed Up With'), ('Successfully Booked', 'Successfully Booked (B)'), ('Not Going To Work', 'Not Going To Work (X)')], default='Not Contacted', max_length=30),
        ),
    ]
