# Generated by Django 4.0.6 on 2022-08-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_venue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='status',
            field=models.CharField(max_length=150),
        ),
    ]
